spring:
  application:
    name: user-application
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/sm_user_db
    username: testuser
    password: testuser@123
    driverClassName: com.mysql.jdbc.Driver
        
server:
  port: 8073
  contextPath: /user-application

eureka:
  client:
    registerWithEureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost  

